# Generated by Django 3.2 on 2021-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskDeadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskHasChild',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskParent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskPercentComplete',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskStatus',
            field=models.CharField(default='backlog', max_length=15),
        ),
    ]
