# Generated by Django 3.2 on 2021-05-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTM', '0002_auto_20210520_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='memberIsAssignedTask',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskPriority',
            field=models.IntegerField(choices=[(2, 'Low Impact - High Urgency'), (4, 'Low Impact - Low Urgency'), (1, 'High Impact - High Urgency'), (3, 'High Impact - Low Urgency')], default=4),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskStatus',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('In Progress', 'Inprogress'), ('Blocked', 'Blocked'), ('Complete', 'Complete')], default='Backlog', max_length=20),
        ),
    ]
